2018-02-11 07:59:34 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-02-11 07:59:34 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 07:59:35 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 07:59:35 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 08:01:23 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:01:23] "POST /playbook HTTP/1.1" 200 -
2018-02-11 08:04:15 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:04:15] "GET /taskstatus/playbook/66294634-1f3e-4738-8936-966d2a340c8f HTTP/1.1" 200 -
2018-02-11 08:08:40 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-02-11 08:08:40 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 08:08:42 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 08:08:42 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 08:09:35 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:09:35] "POST /playbook HTTP/1.1" 200 -
2018-02-11 08:09:46 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:09:46] "GET /taskstatus/playbook/cc5827b3-c726-4406-a409-a457108cac40 HTTP/1.1" 200 -
2018-02-11 08:12:11 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:12:11] "POST /playbook HTTP/1.1" 200 -
2018-02-11 08:12:25 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:12:25] "GET /taskstatus/playbook/6c46c6b5-4f1a-4bf1-97d5-2965f4b68747 HTTP/1.1" 200 -
2018-02-11 08:15:10 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:15:10] "POST /ansiblerun HTTP/1.1" 200 -
2018-02-11 08:15:13 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:15:13] "GET /taskstatus/playbook/6c46c6b5-4f1a-4bf1-97d5-2965f4b68747 HTTP/1.1" 200 -
2018-02-11 08:15:27 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:15:27] "GET /taskstatus/ad_hoc/81d1aa3d-5583-4466-8f34-676e7d919723 HTTP/1.1" 200 -
2018-02-11 08:26:15 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:26:15] "POST /ansiblerun HTTP/1.1" 200 -
2018-02-11 08:26:32 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:26:32] "GET /taskstatus/ad_hoc/683b5d5a-3130-4d4d-a283-4ae27e147539 HTTP/1.1" 200 -
2018-02-11 08:30:19 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:30:19] "POST /ansiblerun HTTP/1.1" 200 -
2018-02-11 08:30:40 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:30:40] "POST /add HTTP/1.1" 200 -
2018-02-11 08:31:16 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:31:16] "POST /add HTTP/1.1" 200 -
2018-02-11 08:31:36 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:31:36] "POST /add HTTP/1.1" 200 -
2018-02-11 08:32:11 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-02-11 08:32:11 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 08:32:13 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 08:32:13 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 08:32:23 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-02-11 08:32:23 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 08:32:24 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 08:32:24 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 08:32:37 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:32:37] "POST /add HTTP/1.1" 200 -
2018-02-11 08:35:36 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-02-11 08:35:36 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 08:35:37 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 08:35:37 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 08:35:46 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-02-11 08:35:46 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 08:35:47 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 08:35:47 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 08:35:58 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:35:58] "POST /add HTTP/1.1" 200 -
2018-02-11 08:36:38 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-02-11 08:36:38 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 08:37:17 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-02-11 08:37:17 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 08:37:19 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 08:37:19 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 08:37:32 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:37:32] "POST /add HTTP/1.1" 200 -
2018-02-11 08:38:16 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-02-11 08:38:16 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 08:38:18 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 08:38:18 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 08:38:29 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-02-11 08:38:29 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 08:38:31 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 08:38:31 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 08:38:44 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:38:44] "POST /ansiblerun HTTP/1.1" 200 -
2018-02-11 08:42:27 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/models/ansible_api.py', reloading
2018-02-11 08:42:27 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 08:42:29 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 08:42:29 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 08:42:42 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-02-11 08:42:42 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 08:42:44 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 08:42:44 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 08:43:02 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 08:43:02] "POST /ansiblerun HTTP/1.1" 200 -
2018-02-11 08:47:00 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/models/ansible_api.py', reloading
2018-02-11 08:47:01 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 08:47:05 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 08:47:05 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 09:53:14 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-02-11 09:53:14 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 09:53:16 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 09:53:16 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 09:53:19 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 09:53:19] "POST /ansiblerun HTTP/1.1" 200 -
2018-02-11 10:04:01 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 10:04:01] "POST /ansiblerun HTTP/1.1" 200 -
2018-02-11 10:04:52 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 10:04:52] "POST /ansiblerun HTTP/1.1" 200 -
2018-02-11 10:06:17 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-02-11 10:06:17 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 10:06:19 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 10:06:19 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 10:06:21 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 10:06:21] "POST /ansiblerun HTTP/1.1" 200 -
2018-02-11 10:07:02 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 10:07:02] "GET /taskstatus/ad_hoc/28e616f7-f8fc-4c08-9a49-d95f2afd9a03 HTTP/1.1" 200 -
2018-02-11 10:08:14 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 10:08:14] "POST /playbook HTTP/1.1" 200 -
2018-02-11 10:09:27 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/models/ansible_api.py', reloading
2018-02-11 10:09:27 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 10:09:40 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-02-11 10:09:40 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 10:09:42 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 10:09:42 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 10:09:42 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 10:09:42] "POST /playbook HTTP/1.1" 200 -
2018-02-11 10:10:08 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/models/ansible_api.py', reloading
2018-02-11 10:10:09 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 10:10:11 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 10:10:11 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 10:10:16 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 10:10:16] "POST /playbook HTTP/1.1" 200 -
2018-02-11 10:10:56 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/models/ansible_api.py', reloading
2018-02-11 10:10:56 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 10:11:00 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 10:11:00 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 10:11:18 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/models/ansible_api.py', reloading
2018-02-11 10:11:18 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 10:11:21 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 10:11:21 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 10:16:12 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/models/ansible_api.py', reloading
2018-02-11 10:16:13 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 10:16:16 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 10:16:16 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 10:18:11 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/models/ansible_api.py', reloading
2018-02-11 10:18:12 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 10:18:15 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 10:18:15 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 10:21:25 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 10:21:25] "POST /playbook HTTP/1.1" 200 -
2018-02-11 10:21:37 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-02-11 10:21:37 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-02-11 10:21:39 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-02-11 10:21:39 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 239-139-087
2018-02-11 10:21:46 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [11/Feb/2018 10:21:46] "POST /playbook HTTP/1.1" 200 -
2018-04-03 19:12:34 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-03 19:12:34 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 19:12:35 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 19:12:35 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 19:13:12 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 19:13:12] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 19:14:09 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/AutomateOperation-Ansible_2.4_asyn_api-master/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-03 19:14:09 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 19:14:10 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 19:14:10 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 19:14:13 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 19:14:13] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 19:15:12 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 19:15:12] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 19:15:30 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 19:15:30] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 19:16:02 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 19:16:02] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 19:16:56 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/AutomateOperation-Ansible_2.4_asyn_api-master/models/ansible_api.py', reloading
2018-04-03 19:16:56 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 19:16:58 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 19:16:58 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 19:17:13 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/AutomateOperation-Ansible_2.4_asyn_api-master/models/ansible_api.py', reloading
2018-04-03 19:17:13 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 19:17:15 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 19:17:15 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 19:17:37 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/AutomateOperation-Ansible_2.4_asyn_api-master/models/ansible_api.py', reloading
2018-04-03 19:17:37 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 19:17:39 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 19:17:39 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 19:17:56 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/AutomateOperation-Ansible_2.4_asyn_api-master/models/ansible_api.py', reloading
2018-04-03 19:17:56 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 19:17:58 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 19:17:58 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 22:12:51 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-03 22:12:51 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 22:12:53 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 22:12:53 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 22:14:16 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:14:16] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 22:18:00 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/AutomateOperation-Ansible_2.4_asyn_api-master/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-03 22:18:00 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 22:21:01 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-03 22:21:01 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 22:21:02 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 22:21:02 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 22:21:26 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:21:26] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 22:21:57 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:21:57] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-03 22:22:02 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:22:02] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-03 22:22:06 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:22:06] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 22:23:35 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/AutomateOperation-Ansible_2.4_asyn_api-master/models/runner.py', reloading
2018-04-03 22:23:35 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 22:23:37 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 22:23:37 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 22:23:58 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:23:58] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 22:24:20 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:24:20] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 22:26:03 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:26:03] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 22:26:17 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-03 22:26:17 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 22:26:18 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 22:26:18 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 22:26:20 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:26:20] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 22:29:45 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-03 22:29:45 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 22:29:47 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 22:29:47 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 22:29:48 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:29:48] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 22:32:22 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:32:22] "GET /taskstatus/ad_hoc/d58b2926-1e6c-4bd2-bc8f-10375a17f681 HTTP/1.1" 200 -
2018-04-03 22:34:41 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-03 22:34:41 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 22:34:42 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 22:34:42 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 22:34:44 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:34:44] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 22:34:56 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:34:56] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 22:35:20 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:35:20] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 22:37:41 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/AutomateOperation-Ansible_2.4_asyn_api-master/models/ansible_api.py', reloading
2018-04-03 22:37:41 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 22:37:43 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 22:37:43 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 22:38:07 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:38:07] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 22:38:47 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/AutomateOperation-Ansible_2.4_asyn_api-master/models/ansible_api.py', reloading
2018-04-03 22:38:47 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 22:38:49 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 22:38:49 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 22:38:50 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:38:50] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 22:39:05 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:39:05] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-03 22:40:08 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/AutomateOperation-Ansible_2.4_asyn_api-master/models/ansible_api.py', reloading
2018-04-03 22:40:08 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 22:40:11 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 22:40:11 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 22:40:34 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:40:34] "POST /playbook HTTP/1.1" 200 -
2018-04-03 22:43:43 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-03 22:43:43 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 22:43:44 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 22:43:44 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 22:43:44 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:43:44] "POST /playbook HTTP/1.1" 200 -
2018-04-03 22:45:11 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-03 22:45:11 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 22:45:13 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 22:45:13 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 22:45:20 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:45:20] "POST /playbook HTTP/1.1" 200 -
2018-04-03 22:47:22 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-03 22:47:22 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-03 22:47:24 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-03 22:47:24 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-03 22:47:27 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:47:27] "POST /playbook HTTP/1.1" 200 -
2018-04-03 22:47:50 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:47:50] "POST /playbook HTTP/1.1" 200 -
2018-04-03 22:47:55 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [03/Apr/2018 22:47:55] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 10:43:26 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-04 10:43:26 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 10:43:28 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 10:43:28 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 634-227-554
2018-04-04 10:43:54 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 10:43:54] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 10:48:45 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 10:48:45] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 11:00:52 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-04 11:00:53 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 11:00:55 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 11:00:55 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 852-966-929
2018-04-04 11:00:55 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 11:00:55] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 15:02:38 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-04 15:02:38 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:02:40 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:02:40 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:02:58 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:02:58] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 15:03:20 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:03:20] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-04 15:03:29 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:03:29] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 15:05:38 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:05:38] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 15:05:57 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-04 15:05:57 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:05:59 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:05:59 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:05:59 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:05:59] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 15:06:02 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:06:02] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 15:06:46 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/FlaskAnsibleCall.py', reloading
2018-04-04 15:06:46 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:06:48 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:06:48 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:07:05 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-04 15:07:05 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:07:06 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:07:06 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:07:07 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:07:07] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 15:07:47 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-04 15:07:47 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:07:49 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:07:49 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:07:54 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-04 15:07:54 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:07:55 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:07:55 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:07:57 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:07:57] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 15:08:41 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-04 15:08:41 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:08:42 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:08:42 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:08:49 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:08:49] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 15:09:39 - _internal.py:88(_internal:_log) - INFO - 192.168.213.100 - - [04/Apr/2018 15:09:39] "GET /taskstatus/ad_hoc/0ae235da-781c-4443-a80f-a3b57472d6ec HTTP/1.1" 200 -
2018-04-04 15:09:40 - _internal.py:88(_internal:_log) - INFO - 192.168.213.100 - - [04/Apr/2018 15:09:40] "GET /favicon.ico HTTP/1.1" 404 -
2018-04-04 15:10:54 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-04 15:10:54 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:10:56 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:10:56 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:11:21 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:11:21] "POST /playbook HTTP/1.1" 400 -
2018-04-04 15:11:30 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:11:30] "POST /playbook HTTP/1.1" 400 -
2018-04-04 15:11:34 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:11:34] "POST /playbook HTTP/1.1" 400 -
2018-04-04 15:11:49 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:11:49] "POST /playbook HTTP/1.1" 400 -
2018-04-04 15:12:27 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:12:27] "POST /playbook HTTP/1.1" 200 -
2018-04-04 15:13:09 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-04 15:13:09 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:13:10 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:13:10 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:13:16 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:13:16] "POST /playbook HTTP/1.1" 200 -
2018-04-04 15:14:31 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:14:31] "POST /playbook HTTP/1.1" 400 -
2018-04-04 15:14:35 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:14:35] "POST /playbook HTTP/1.1" 200 -
2018-04-04 15:14:58 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-04 15:14:58 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:14:59 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:14:59 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:15:11 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:15:11] "POST /playbook HTTP/1.1" 200 -
2018-04-04 15:15:34 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-04 15:15:34 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:15:35 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:15:35 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:15:57 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-04 15:15:57 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:15:59 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:15:59 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:16:04 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:16:04] "POST /playbook HTTP/1.1" 200 -
2018-04-04 15:16:32 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-04 15:16:32 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:16:34 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:16:34 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:16:38 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:16:38] "POST /playbook HTTP/1.1" 200 -
2018-04-04 15:18:39 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:18:39] "POST /playbook HTTP/1.1" 200 -
2018-04-04 15:18:56 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-04 15:18:56 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:18:57 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:18:57 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:19:03 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:19:03] "POST /playbook HTTP/1.1" 200 -
2018-04-04 15:19:24 - _internal.py:88(_internal:_log) - INFO - 192.168.213.100 - - [04/Apr/2018 15:19:24] "GET /taskstatus/playbook/37520499-b373-4b04-ae1a-0264673e4334 HTTP/1.1" 200 -
2018-04-04 15:21:48 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-04 15:21:48 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:21:49 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:21:49 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:21:51 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:21:51] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 15:21:57 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:21:57] "POST /playbook HTTP/1.1" 200 -
2018-04-04 15:23:04 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:23:04] "POST /playbook HTTP/1.1" 200 -
2018-04-04 15:23:25 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-04 15:23:25 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:23:26 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:23:26 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:23:26 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:23:26] "POST /playbook HTTP/1.1" 200 -
2018-04-04 15:25:10 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-04 15:25:10 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:25:12 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:25:12 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:25:18 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-04 15:25:18 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:25:20 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:25:20 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:25:20 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:25:20] "POST /playbook HTTP/1.1" 200 -
2018-04-04 15:25:59 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:25:59] "POST /playbook HTTP/1.1" 200 -
2018-04-04 15:26:09 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-04 15:26:10 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:26:11 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:26:11 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:26:17 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:26:17] "POST /playbook HTTP/1.1" 200 -
2018-04-04 15:27:45 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-04 15:27:45 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:27:46 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:27:46 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:27:52 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-04 15:27:52 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:27:53 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:27:53 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:27:53 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:27:53] "POST /playbook HTTP/1.1" 200 -
2018-04-04 15:28:44 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-04 15:28:44 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:28:46 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:28:46 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:28:52 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-04 15:28:52 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:28:53 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:28:53 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:28:53 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:28:53] "POST /playbook HTTP/1.1" 200 -
2018-04-04 15:29:10 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-04 15:29:11 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:29:12 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:29:12 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:29:16 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:29:16] "POST /playbook HTTP/1.1" 200 -
2018-04-04 15:32:40 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/models/runner.py', reloading
2018-04-04 15:32:40 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:32:43 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:32:43 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:37:44 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-04 15:37:44 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:37:45 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:37:45 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:38:03 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-04 15:38:03 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:38:04 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:38:04 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:39:02 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:39:02] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 15:40:32 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/models/runner.py', reloading
2018-04-04 15:40:32 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:42:04 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-04 15:42:05 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 15:42:06 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 15:42:06 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 104-307-732
2018-04-04 15:42:07 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 15:42:07] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 15:47:42 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/models/callback.py', reloading
2018-04-04 15:47:43 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 16:15:59 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-04 16:15:59 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 16:16:00 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 16:16:00 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 195-173-001
2018-04-04 16:16:06 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 16:16:06] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 16:16:32 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-04 16:16:32 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 16:16:33 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 16:16:33 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 195-173-001
2018-04-04 16:16:52 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 16:16:52] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 16:18:36 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-04 16:18:36 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 16:18:38 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 16:18:38 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 195-173-001
2018-04-04 16:18:49 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-04 16:18:49 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 16:18:50 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 16:18:50 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 195-173-001
2018-04-04 16:18:58 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 16:18:58] "POST /playbook HTTP/1.1" 200 -
2018-04-04 16:23:13 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/models/runner.py', reloading
2018-04-04 16:23:13 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 16:23:15 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 16:23:15 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 195-173-001
2018-04-04 16:23:27 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-04 16:23:27 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 16:23:28 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 16:23:28 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 195-173-001
2018-04-04 16:23:32 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 16:23:32] "POST /playbook HTTP/1.1" 200 -
2018-04-04 16:24:55 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 16:24:55] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 16:25:32 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 16:25:32] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 16:26:09 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 16:26:09] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 16:26:33 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 16:26:33] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 16:27:08 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 16:27:08] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 16:27:28 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 16:27:28] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 16:27:51 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [04/Apr/2018 16:27:51] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-04 16:51:23 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/models/runner.py', reloading
2018-04-04 16:51:24 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 16:51:25 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 16:51:25 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 195-173-001
2018-04-04 17:30:09 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/config.py', reloading
2018-04-04 17:30:10 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 17:30:12 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 17:30:12 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 195-173-001
2018-04-04 17:31:42 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/config.py', reloading
2018-04-04 17:31:42 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 17:31:44 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 17:31:44 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 195-173-001
2018-04-04 17:32:16 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/config.py', reloading
2018-04-04 17:32:16 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-04 17:32:18 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-04 17:32:18 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 195-173-001
2018-04-07 20:28:07 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-07 20:28:08 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-07 20:28:10 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-07 20:28:10 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 195-173-001
2018-04-08 09:05:21 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-08 09:05:21 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 09:05:23 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 09:05:23 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 09:05:58 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 09:05:58] "POST /playbook HTTP/1.1" 200 -
2018-04-08 09:06:17 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 09:06:17] "POST /playbook HTTP/1.1" 400 -
2018-04-08 09:06:23 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 09:06:23] "POST /playbook HTTP/1.1" 200 -
2018-04-08 09:07:19 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 09:07:19] "POST /playbook HTTP/1.1" 200 -
2018-04-08 09:08:42 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 09:08:42] "POST /playbook HTTP/1.1" 200 -
2018-04-08 09:08:59 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 09:08:59] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 09:09:11 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 09:09:11] "POST /playbook HTTP/1.1" 200 -
2018-04-08 09:09:46 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 09:09:46] "POST /playbook HTTP/1.1" 200 -
2018-04-08 09:10:31 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 09:10:31] "POST /playbook HTTP/1.1" 200 -
2018-04-08 09:11:07 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 09:11:07] "POST /playbook HTTP/1.1" 200 -
2018-04-08 09:12:29 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 09:12:29] "POST /playbook HTTP/1.1" 200 -
2018-04-08 09:12:45 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 09:12:45] "POST /playbook HTTP/1.1" 200 -
2018-04-08 09:13:12 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 09:13:12] "POST /playbook HTTP/1.1" 200 -
2018-04-08 09:19:34 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/config.py', reloading
2018-04-08 09:19:34 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 09:19:35 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 09:19:35 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 09:19:48 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-08 09:19:48 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 09:19:49 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 09:19:49 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 09:19:58 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 09:19:58] "POST /playbook HTTP/1.1" 200 -
2018-04-08 09:27:26 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/utilites/__init__.py', reloading
2018-04-08 09:27:26 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 09:27:28 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 09:27:28 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 09:28:05 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-08 09:28:05 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 09:28:06 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 09:28:06 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 09:28:10 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 09:28:10] "POST /playbook HTTP/1.1" 200 -
2018-04-08 09:28:43 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 09:28:43] "POST /playbook HTTP/1.1" 200 -
2018-04-08 10:04:23 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/config.py', reloading
2018-04-08 10:04:23 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 10:04:25 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 10:04:25 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 11:21:22 - _internal.py:88(_internal:_log) - INFO - 192.168.213.129 - - [08/Apr/2018 11:21:22] "GET /taskstatus/playbook/53686584-ea25-4fad-8818-59c03db158bd HTTP/1.1" 200 -
2018-04-08 11:22:29 - _internal.py:88(_internal:_log) - INFO - 192.168.213.129 - - [08/Apr/2018 11:22:29] "GET /taskstatus/ad_hoc/9b3f160a-439c-40ad-a40b-64dc7dc6f03f HTTP/1.1" 200 -
2018-04-08 11:40:47 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-08 11:40:47 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 11:40:49 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 11:40:49 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 11:40:57 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-08 11:40:57 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 11:40:59 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 11:40:59 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 11:41:10 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 11:41:10] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 11:41:31 - _internal.py:88(_internal:_log) - INFO - 192.168.213.129 - - [08/Apr/2018 11:41:31] "GET /taskstatus/ad_hoc/a61be96b-26f4-433f-9479-db9d693042e9 HTTP/1.1" 200 -
2018-04-08 11:41:53 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-08 11:41:53 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 11:41:55 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 11:41:55 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 11:44:14 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-08 11:44:14 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 11:44:16 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 11:44:16 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 11:44:17 - _internal.py:88(_internal:_log) - INFO - 192.168.213.129 - - [08/Apr/2018 11:44:17] "GET /taskstatus/ad_hoc/a61be96b-26f4-433f-9479-db9d693042e9 HTTP/1.1" 200 -
2018-04-08 11:44:24 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 11:44:24] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 11:44:38 - _internal.py:88(_internal:_log) - INFO - 192.168.213.129 - - [08/Apr/2018 11:44:38] "GET /taskstatus/ad_hoc/7ad481bb-ca10-4ad6-9e1f-a301cafa5a6d HTTP/1.1" 200 -
2018-04-08 11:44:58 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 11:44:58] "POST /playbook HTTP/1.1" 200 -
2018-04-08 11:46:18 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-08 11:46:18 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 11:46:20 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 11:46:20 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 11:46:34 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 11:46:34] "POST /ansibleru HTTP/1.1" 404 -
2018-04-08 11:46:36 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 11:46:36] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 11:47:02 - _internal.py:88(_internal:_log) - INFO - 192.168.213.129 - - [08/Apr/2018 11:47:02] "GET /taskstatus/ad_hoc/ad0ab3ca-008d-4f54-bec2-513c4e639a5e HTTP/1.1" 200 -
2018-04-08 11:48:16 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-08 11:48:16 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 11:48:17 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 11:48:17 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 11:48:19 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 11:48:19] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 11:48:31 - _internal.py:88(_internal:_log) - INFO - 192.168.213.129 - - [08/Apr/2018 11:48:31] "GET /taskstatus/ad_hoc/2fa8c536-d762-4c22-9193-f18b240a9e2c HTTP/1.1" 200 -
2018-04-08 11:53:42 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-08 11:53:42 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 11:53:44 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 11:53:44 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 11:53:48 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 11:53:48] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 11:53:52 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 11:53:52] "POST /playbook HTTP/1.1" 200 -
2018-04-08 11:54:20 - _internal.py:88(_internal:_log) - INFO - 192.168.213.129 - - [08/Apr/2018 11:54:20] "GET /taskstatus/playbook/cbaaaac4-e4f0-47ee-aef3-e1cf5c15d754 HTTP/1.1" 200 -
2018-04-08 11:54:36 - _internal.py:88(_internal:_log) - INFO - 192.168.213.100 - - [08/Apr/2018 11:54:36] "GET /taskstatus/playbook/cbaaaac4-e4f0-47ee-aef3-e1cf5c15d754 HTTP/1.1" 200 -
2018-04-08 11:54:36 - _internal.py:88(_internal:_log) - INFO - 192.168.213.100 - - [08/Apr/2018 11:54:36] "GET /favicon.ico HTTP/1.1" 404 -
2018-04-08 14:26:25 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-08 14:26:25 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 14:26:26 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 14:26:26 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 14:27:05 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:27:05] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 14:28:08 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:28:08] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 14:28:28 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:28:28] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 14:28:50 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:28:50] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 14:30:06 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:30:06] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 14:30:19 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:30:19] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 14:37:33 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:37:33] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 14:39:03 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:39:03] "POST /playbook HTTP/1.1" 400 -
2018-04-08 14:39:09 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:39:09] "POST /playbook HTTP/1.1" 200 -
2018-04-08 14:39:33 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:39:33] "POST /playbook HTTP/1.1" 400 -
2018-04-08 14:40:05 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:40:05] "POST /playbook HTTP/1.1" 200 -
2018-04-08 14:40:20 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:40:20] "POST /playbook HTTP/1.1" 200 -
2018-04-08 14:40:38 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:40:38] "POST /playbook HTTP/1.1" 200 -
2018-04-08 14:44:53 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/app/tasks/CeleryAnsibleCall.py', reloading
2018-04-08 14:44:53 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 14:44:56 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 14:44:56 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 14:46:07 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-08 14:46:07 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 14:46:08 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 14:46:08 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 14:49:20 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:49:20] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 14:49:28 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:49:28] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 14:49:34 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:49:34] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 14:49:37 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:49:37] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 14:49:41 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:49:41] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 14:50:28 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:50:28] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 14:52:00 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:52:00] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 14:52:27 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:52:27] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 14:53:04 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:53:04] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 14:57:29 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:57:29] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 14:58:13 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:58:13] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 14:58:35 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:58:35] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 14:59:20 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 14:59:20] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 15:00:25 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:00:25] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 15:01:14 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:01:14] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 15:02:10 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:02:10] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 15:04:59 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:04:59] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 15:05:03 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:05:03] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 15:05:08 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:05:08] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 15:05:24 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:05:24] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 15:08:52 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:08:52] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 15:08:59 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:08:59] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 15:09:04 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:09:04] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 15:09:22 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:09:22] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 15:09:27 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:09:27] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 15:10:11 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:10:11] "POST /palybook HTTP/1.1" 404 -
2018-04-08 15:10:31 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:10:31] "POST /palybook HTTP/1.1" 404 -
2018-04-08 15:10:46 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:10:46] "POST /playbook HTTP/1.1" 400 -
2018-04-08 15:10:50 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:10:50] "POST /playbook HTTP/1.1" 400 -
2018-04-08 15:12:04 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:12:04] "POST /playbook HTTP/1.1" 400 -
2018-04-08 15:13:56 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:13:56] "POST /playbook HTTP/1.1" 400 -
2018-04-08 15:14:32 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:14:32] "POST /playbook HTTP/1.1" 200 -
2018-04-08 15:15:31 - _internal.py:88(_internal:_log) - INFO - 192.168.213.100 - - [08/Apr/2018 15:15:31] "GET /taskstatus/playbook/d764fc8f-d9a9-46b5-8890-77bbe2c264ee HTTP/1.1" 200 -
2018-04-08 15:15:55 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:15:55] "POST /playbook HTTP/1.1" 200 -
2018-04-08 15:16:22 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:16:22] "POST /playbook HTTP/1.1" 200 -
2018-04-08 15:20:29 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:20:29] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 15:20:45 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:20:45] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 15:21:14 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:21:14] "POST /ansiblerun HTTP/1.1" 400 -
2018-04-08 15:21:49 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:21:49] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 15:22:24 - _internal.py:88(_internal:_log) - INFO - 192.168.213.100 - - [08/Apr/2018 15:22:24] "GET /taskstatus/ad_hoc/31aad68f-88c4-44b0-ac2a-cbdad34ae40d HTTP/1.1" 200 -
2018-04-08 15:23:07 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/models/ansible_api.py', reloading
2018-04-08 15:23:07 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 15:23:10 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 15:23:10 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 15:23:15 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-08 15:23:15 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 15:23:17 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 15:23:17 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 15:23:32 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:23:32] "POST /playbook HTTP/1.1" 200 -
2018-04-08 15:24:11 - _internal.py:88(_internal:_log) - INFO - 192.168.213.100 - - [08/Apr/2018 15:24:11] "GET /taskstatus/playbook/7ebd909f-027b-4815-8626-35c20cc33d8b HTTP/1.1" 200 -
2018-04-08 15:24:25 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/models/ansible_api.py', reloading
2018-04-08 15:24:25 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 15:24:27 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 15:24:27 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 15:24:41 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-08 15:24:41 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 15:24:42 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 15:24:42 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 15:24:56 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:24:56] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 15:25:13 - _internal.py:88(_internal:_log) - INFO - 192.168.213.100 - - [08/Apr/2018 15:25:13] "GET /taskstatus/ad_hoc/948fca8e-3c22-4530-83b0-b457458bef38 HTTP/1.1" 200 -
2018-04-08 15:25:40 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:25:40] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 15:26:09 - _internal.py:88(_internal:_log) - INFO - 192.168.213.100 - - [08/Apr/2018 15:26:09] "GET /taskstatus/ad_hoc/4e755e35-a38b-4f06-b973-beeaa8fbc002 HTTP/1.1" 200 -
2018-04-08 15:37:18 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-08 15:37:18 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 15:37:20 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 15:37:20 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 15:37:41 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:37:41] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 15:37:57 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:37:57] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 15:39:16 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:39:16] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 15:41:12 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:41:12] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 15:45:27 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:45:27] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 15:45:56 - _internal.py:88(_internal:_log) - INFO - 192.168.213.100 - - [08/Apr/2018 15:45:56] "GET /taskstatus/ad_hoc/d8a13c9e-840f-4b8c-b4bd-68db4088cf67 HTTP/1.1" 200 -
2018-04-08 15:46:28 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:46:28] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-08 15:47:13 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 15:47:13] "POST /playbook HTTP/1.1" 200 -
2018-04-08 15:50:47 - _internal.py:88(_internal:_log) - INFO - 192.168.213.129 - - [08/Apr/2018 15:50:47] "GET /taskstatus/playbook/b002c492-1e96-40cf-a1d9-e09a3a524be9 HTTP/1.1" 200 -
2018-04-08 15:59:45 - _internal.py:88(_internal:_log) - INFO -  * Detected change in '/root/PycharmProjects/ansible_2.4_asyn_api/models/__init__.py', reloading
2018-04-08 15:59:46 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 16:00:37 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-08 16:00:37 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-08 16:00:38 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-08 16:00:38 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 108-746-399
2018-04-08 16:00:42 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [08/Apr/2018 16:00:42] "POST /playbook HTTP/1.1" 200 -
2018-04-09 15:28:30 - _internal.py:88(_internal:_log) - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-04-09 15:28:30 - _internal.py:88(_internal:_log) - INFO -  * Restarting with stat
2018-04-09 15:28:32 - _internal.py:88(_internal:_log) - WARNING -  * Debugger is active!
2018-04-09 15:28:32 - _internal.py:88(_internal:_log) - INFO -  * Debugger PIN: 243-813-481
2018-04-09 15:28:48 - _internal.py:88(_internal:_log) - INFO - 127.0.0.1 - - [09/Apr/2018 15:28:48] "POST /ansiblerun HTTP/1.1" 200 -
2018-04-09 15:33:28 - _internal.py:88(_internal:_log) - INFO - 192.168.213.100 - - [09/Apr/2018 15:33:28] "GET /taskstatus/ad_hoc/fff15223-b562-48e8-a621-a553b9a2edfd HTTP/1.1" 200 -
2018-04-09 15:33:28 - _internal.py:88(_internal:_log) - INFO - 192.168.213.100 - - [09/Apr/2018 15:33:28] "GET /favicon.ico HTTP/1.1" 404 -
